version: "3.9"
services:
  nginx:
    build: ./nginx
    image: nginx-custom
    container_name: nginx-cont
    ports:
      - "80:80"
    restart: always
    networks:
      - net-app
    depends_on:
      django:
        condition: service_healthy

  django:
    build: .
    image: django-custom
    container_name: django_app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - net-app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    container_name: db_cont
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-proot"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always
    networks:
      - net-app
    volumes:
      - ./mysql-data:/var/lib/mysql

networks:
  net-app:
    driver: bridge
